### ISSUE TITLE
What does this line do ?

### ISSUE THREAD

**Issue by davecramer** [dpage/winpgbuild#19]
https://github.com/dpage/winpgbuild/blob/422664c490fee9e05c1d54ae51a9a5cc15acf57c/.github/workflows/meson.yml#L21

I've tried this on latest versions of windows and both fail with `The token '||' is not a valid statement separator in this version.`

**Comment by anarazel** [comment]
It should probably be removed.

On some versions of powershell (as well as unix shells) this just hides potential failures of the command.

**Comment by dpage** [comment]
Fixed in 6e9faa6658854ca0fadf535a67005c25b766d384
