### ISSUE TITLE
versions of files are not visible

### ISSUE THREAD

**Issue by davecramer** [dpage/winpgbuild#20]
As repository variables we can't see what versions are being used

**Comment by dpage** [comment]
Hmm, good point. We should probably generate some kind of manifest in the artefacts we upload.

**Comment by davecramer** [comment]
So it would appear in order to make this workflow reusable we will have to have the versions somewhere besides repository variables https://github.com/davecramer/testbuildpostgres/actions/runs/9896962475

**Comment by dpage** [comment]
I think it's more accurate to say that you have to manually define the versions in every repo clone. 

However, it certainly wouldn't be a bad thing to put the config in the repo.

I'm going to close out this issue, and create two new ones to cover how we store the config, and how we document what's in artefacts we create, as those two issues have become somewhat conflated on multiple existing issue/PR discussions.
